### ISSUE TITLE
Uploads 15-9-15

### ISSUE THREAD

**Issue by cunothe1** [nasserievermeij/nasserievermeij.github.io#3]
![flipping_verkrekt_logo](https://cloud.githubusercontent.com/assets/15033484/10537052/bdffa818-73ef-11e5-9199-47044e095a22.png)

**Comment by cunothe1** [comment]
shit logo

**Comment by ev1l0rd** [comment]
Ok!

**Comment by cunothe1** [comment]
kut niels
