### ISSUE TITLE
10-11-2015 Uploads

### ISSUE THREAD

**Issue by ev1l0rd** [nasserievermeij/nasserievermeij.github.io#4]
![bg](https://cloud.githubusercontent.com/assets/13433513/11059390/ad2527c6-8799-11e5-9019-2e6b0c32ec66.jpg)

**Comment by cunothe1** [comment]
![drawing 6](https://cloud.githubusercontent.com/assets/15033484/11060338/c46faf4a-879f-11e5-91e4-96a30940116a.png)
hoi valentijn jij doet eens iets goeds

**Comment by cunothe1** [comment]
![drawing 7](https://cloud.githubusercontent.com/assets/15033484/11060396/405deafe-87a0-11e5-8687-49ce0d2269fc.png)
nieuw dingetje

**Comment by cunothe1** [comment]
ev1l0rd locked and limited conversation to collaborators 6 days ago
wat is dat?
